---
Name: restfulapi
After: 
  - 'framework/*'
  - 'cms/*'
---
# ---------------------------------
# Routing
SilverStripe\Control\Director:
  rules:
    'api': 'colymba\RESTfulAPI\RESTfulAPI'
# ---------------------------------
# Permissions / Uncomment or create your own
#SilverStripe\Security\Group:
#  extensions:
#    - colymba\RESTfulAPI\Extensions\RESTfulAPIGroupExtension