---
Name: restfulapi
After: 'framework/*','cms/*'
---
# ---------------------------------
# Routing
SilverStripe\Control\Director:
  rules:
    'api': 'DNADesign\RESTfulAPI\RESTfulAPI'
# ---------------------------------
# Permissions / Uncomment or create your own
#SilverStripe\Security\Group:
#  extensions:
#    - DNADesign\RESTfulAPI\Extensions\RESTfulAPIGroupExtension